<?php
declare(strict_types=1);

// DnsLookup SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DnsLookupUtility::setRegistrar(function (DnsLookupUtility $u): void {
    $u->clean = [DnsLookupClean::class, 'call'];
    $u->done = [DnsLookupDone::class, 'call'];
    $u->make_error = [DnsLookupMakeError::class, 'call'];
    $u->feature_add = [DnsLookupFeatureAdd::class, 'call'];
    $u->feature_hook = [DnsLookupFeatureHook::class, 'call'];
    $u->feature_init = [DnsLookupFeatureInit::class, 'call'];
    $u->fetcher = [DnsLookupFetcher::class, 'call'];
    $u->make_fetch_def = [DnsLookupMakeFetchDef::class, 'call'];
    $u->make_context = [DnsLookupMakeContext::class, 'call'];
    $u->make_options = [DnsLookupMakeOptions::class, 'call'];
    $u->make_request = [DnsLookupMakeRequest::class, 'call'];
    $u->make_response = [DnsLookupMakeResponse::class, 'call'];
    $u->make_result = [DnsLookupMakeResult::class, 'call'];
    $u->make_point = [DnsLookupMakePoint::class, 'call'];
    $u->make_spec = [DnsLookupMakeSpec::class, 'call'];
    $u->make_url = [DnsLookupMakeUrl::class, 'call'];
    $u->param = [DnsLookupParam::class, 'call'];
    $u->prepare_auth = [DnsLookupPrepareAuth::class, 'call'];
    $u->prepare_body = [DnsLookupPrepareBody::class, 'call'];
    $u->prepare_headers = [DnsLookupPrepareHeaders::class, 'call'];
    $u->prepare_method = [DnsLookupPrepareMethod::class, 'call'];
    $u->prepare_params = [DnsLookupPrepareParams::class, 'call'];
    $u->prepare_path = [DnsLookupPreparePath::class, 'call'];
    $u->prepare_query = [DnsLookupPrepareQuery::class, 'call'];
    $u->graphql_body = [DnsLookupGraphql::class, 'body'];
    $u->graphql_errors = [DnsLookupGraphql::class, 'errors'];
    $u->result_basic = [DnsLookupResultBasic::class, 'call'];
    $u->result_body = [DnsLookupResultBody::class, 'call'];
    $u->result_headers = [DnsLookupResultHeaders::class, 'call'];
    $u->transform_request = [DnsLookupTransformRequest::class, 'call'];
    $u->transform_response = [DnsLookupTransformResponse::class, 'call'];
});
